const SERVER_MESSAGE_MAP: Record<string, string> = {
  Common_401: "Chưa xác thực",
  Common_403: "Chưa có quyền",
  Common_404: "Không tìm thấy",
  Common_500: "Lỗi server",
  Common_501: "Thiếu tham số",
  Auth_000: "Sai tài khoản hoặc mật khẩu",
  Auth_001: "Tài khoản đã bị khóa",
  Auth_002: "Đăng nhập thành công",
  Auth_003: "Đăng xuất thành công",
  Auth_004: "Cập nhật hồ sơ thành công",
  Auth_005: "Email đã được sử dụng",
  Auth_006: "Token không hợp lệ",
  Auth_007: "Refresh token không hợp lệ",
  Auth_008: "Refresh token không khớp",
  Auth_009: "Refresh token đã hết hạn",
  Auth_010: "Trao đổi token Google thất bại",
  Auth_011: "Thiếu id token từ Google",
  Auth_012: "Thiếu mã xác thực từ Google",
  Auth_013: "Đăng nhập thất bại",
  User_000: "Không tìm thấy người dùng",
  User_001: "Lấy hồ sơ người dùng thành công",
  User_002: "Người dùng chưa có địa điểm tương tác gần đây",
  User_003: "Lấy địa điểm gần đây thành công",
  User_004: "Lấy danh sách người dùng thành công",
  User_005: "Lấy thông tin người dùng thành công",
  User_006: "Tạo người dùng thành công",
  User_007: "Cập nhật người dùng thành công",
  User_008: "Khóa người dùng thành công",
  User_009: "Mở khóa người dùng thành công",
  Location_000: "Không tìm thấy địa điểm",
  Location_001: "Lấy danh sách địa điểm thành công",
  Location_002: "Lấy chi tiết địa điểm thành công",
  Location_003: "Lấy danh sách đánh giá của địa điểm thành công",
  Location_004: "Tạo địa điểm thành công và đang chờ duyệt",
  Location_005: "Gửi yêu cầu cập nhật địa điểm thành công",
  Location_006: "Bạn không có quyền cập nhật địa điểm này",
  Location_007: "Địa điểm ngừng hoạt động không thể cập nhật",
  Location_008: "Tên địa điểm là bắt buộc",
  Location_009: "Địa chỉ là bắt buộc",
  Location_010: "Loại địa điểm là bắt buộc",
  Location_011: "Trạng thái là bắt buộc",
  Location_012: "Trạng thái địa điểm không hợp lệ",
  Location_013: "Thời gian phải đúng định dạng hh:mm:ss",
  Location_014: "Lấy danh sách địa điểm quản trị thành công",
  Location_015: "Lấy chi tiết địa điểm quản trị thành công",
  Location_016: "Tạo địa điểm quản trị thành công",
  Location_017: "Cập nhật địa điểm quản trị thành công",
  Location_018: "Ẩn địa điểm thành công",
  Review_000: "Không tìm thấy đánh giá",
  Review_001: "Tạo đánh giá thành công",
  Review_002: "Số sao phải nằm trong khoảng từ 1 đến 5",
  Review_003: "Nội dung đánh giá là bắt buộc",
  Review_004: "Chỉ được tải lên tối đa 3 ảnh",
  Review_005: "Lấy danh sách bình luận đánh giá thành công",
  Review_006: "Trạng thái đánh giá không hợp lệ",
  Review_007: "Lấy danh sách đánh giá quản trị thành công",
  Review_008: "Lấy chi tiết đánh giá quản trị thành công",
  Review_009: "Cập nhật trạng thái đánh giá thành công",
  Review_010: "Ẩn đánh giá thành công",
  Comment_000: "Tạo bình luận thành công",
  Comment_001: "Nội dung bình luận là bắt buộc",
  Comment_002: "Bình luận cha không hợp lệ",
  Report_000: "Lý do báo cáo là bắt buộc",
  Report_001: "Loại đối tượng báo cáo không hợp lệ",
  Report_002: "Mã đối tượng báo cáo là bắt buộc",
  Report_003: "Không tìm thấy đối tượng bị báo cáo",
  Report_004: "Không tìm thấy báo cáo",
  Report_005: "Trạng thái báo cáo không hợp lệ",
  Report_006: "Gửi báo cáo thành công",
  Report_007: "Lấy danh sách báo cáo thành công",
  Report_008: "Lấy chi tiết báo cáo thành công",
  Report_009: "Cập nhật trạng thái báo cáo thành công",
  Upload_000: "Không có tệp được tải lên",
  Upload_001: "Tải tệp lên thành công",
};

export const resolveServerMessage = (message?: string | null) => {
  if (!message) {
    return "";
  }

  return SERVER_MESSAGE_MAP[message] ?? message;
};
